src/directory/urls.py
from django.urls import path
from .views import TeacherListView, TeacherDetailView, SearchResultsView

app_name = 'directory'

urlpatterns = [
    path('', TeacherListView.as_view(), name='listing'),
    path('<int:id>/', TeacherDetailView.as_view(), name='detail'),
    path('search/', SearchResultsView.as_view(), name='search')
]

src/importer/urls.py
from django.urls import path
from .views import import_file_view

app_name = 'importer'

urlpatterns = [
    path('', import_file_view, name='import-files'),
]

src/teachers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('directory.urls', namespace='directory')),
    path('import/', include('importer.urls', namespace='importer')),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/directory/models.py
from django.db import models

# Create your models here.

class Subject(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title


class Teacher(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    image = models.ImageField(null=True, default='media/default.jpg', upload_to='media/profile_pics')
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20)
    room = models.CharField(max_length=200)
    subjects = models.ManyToManyField(to='Subject')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

src/importer/models.py
from django.db import models

class MultipleFiles(models.Model):
    csv_file = models.FileField(upload_to='csv')
    zip_file = models.FileField(upload_to='zip')
    csv_activated = models.BooleanField(default=False)
    zip_extracted = models.BooleanField(default=False)
    uploaded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"File id: {self.id}"

src/directory/forms.py
from django import forms

class SearchForm(forms.Form):
    q = forms.CharField(label="Search", max_length=50)

src/importer/forms.py
from django import forms
from .models import MultipleFiles


class MultipleFileForms(forms.ModelForm):
    class Meta:
        model = MultipleFiles
        fields = ('csv_file', 'zip_file')

src/directory/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .forms import SearchForm
from .models import Teacher

# Create your views here.
class TeacherListView(ListView):
    model = Teacher
    form_class = SearchForm
    

class TeacherDetailView(DetailView):
    model = Teacher
    
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Teacher, id=id_)


class SearchResultsView(ListView):
    model = Teacher
    template_name = 'search_results.html'

    def get_queryset(self):
        q = self.request.GET['q']
        choice = self.request.GET['choice']
        if choice == 'subject':
            return Teacher.objects.filter(subjects__title__istartswith=q)
        return Teacher.objects.filter(last_name__istartswith=q)

src/importer/views.py
from django.shortcuts import render
from directory.models import Teacher, Subject
from .models import MultipleFiles
from .forms import MultipleFileForms
from django.contrib.auth.decorators import login_required
import csv
from zipfile import ZipFile
from teachers.settings import BASE_DIR


# helper function for subject object creation
# can be removed if subjects are added via admin panel
def create_subjects(subject_list):
    subjects_in_db = set(subject[-1] for subject in Subject.objects.values_list())
    subjects_not_present = set(subject_list) - subjects_in_db
    if subjects_not_present:
        for subject in subjects_not_present:
            Subject.objects.create(title=subject)


@login_required
# Create your views here.
def import_file_view(request):
    form = MultipleFileForms(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = MultipleFileForms()
        file_obj = MultipleFiles.objects.filter(csv_activated=False, zip_extracted=False).get()
        csv_file = file_obj.csv_file.path
        zip_file = file_obj.zip_file.path
        with open(csv_file, 'r', encoding='utf-8') as f:
            reader = csv.reader(f)
            for line, row in enumerate(reader):
                if line == 0 or not row[0]:
                    continue
                first_name = row[0]
                last_name = row[1]
                image = 'profile_pics/'+row[2].strip() if row[2].strip() else 'default.jpg'
                email = row[3]
                phone = row[4]
                room = row[5]
                subjects = row[6].title().split(', ')[:5]
                create_subjects(subjects)   # Comment out this line if subjects are added via admin panel
                try:
                    teacher = Teacher.objects.create(
                    first_name = first_name,
                    last_name = last_name,
                    image = image, 
                    email = email,
                    phone = phone,
                    room = room,
                )
                    # teacher.subjects.add(*[Subject.objects.get(title=subject).id for subject in subjects])
                    teacher.subjects.add(
                        *Subject.objects.filter(
                            title__in=subjects
                            ).values_list("id", flat=True))

                except Exception as e:
                    print(e, email)     # Can be improved by using logging module to log errors

        with ZipFile(zip_file, 'r') as f:
            f.extractall(BASE_DIR/'media/profile_pics/')

        file_obj.csv_activated = True
        file_obj.zip_extracted = True
        file_obj.save()
        
    return render(request, 'importer/import.html', {'form': form})

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#43969c">
    <div class="container">
      <a class="navbar-brand" href="{% url 'directory:listing' %}">Teachers Yellow Pages</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'directory:listing' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'importer:import-files' %}">Import Data</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

src/templates/directory/search_results.html
{% extends 'base.html' %}
{% block content %}
    <h1> Search Results </h1>
    <table class="table table-bordered table-hover mt-3">
        <thead class="thead-dark">
            <tr>
                <th class="w-25">Name</th>
                <th class="w-25">Email</th>
                <th class="w-25">Phone</th>
                <th class="w-10">Room</th>
                <th class="w-50">Subjects</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td><a href="{% url 'directory:detail' object.id %}"> {{ object.first_name }} {{ object.last_name }}</td>
                <td>{{ object.email }}</td>
                <td>{{ object.phone }}</td>
                <td>{{ object.room }}</td>
                <td>{{ object.subjects }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>git add

src/templates/directory/teacher_detail.html
{% extends 'base.html' %}
{% load static %}
{% get_media_prefix as MEDIA_URL %}
{% block title %} {{ object.first_name }} {{ object.last_name }} {% endblock %}
{% block content %}
<div class="card mb-5">
	<div class="row no-gutters">
		<div class="col-md-6">
			{% if object.image %}
			<img class="img-fluid" src="{{ object.image.url }}" alt="{{ object.first_name }} {{ object.last_name }}">
			{% else %}
			<img class="img-fluid" src="{{ MEDIA_URL }} default.jpg">
			{% endif %}
		</div>
		<div class="card-body">
			<p class="text-muted mb-0" style="font-size: 12px">First Name:</p>
			<p>{{ object.first_name }}</p>
			<p class="text-muted mb-0" style="font-size: 12px">Last Name:</p>
			<p>{{ object.last_name }}</p>
			<p class="text-muted mb-0" style="font-size: 12px">Email:</p>
			<p>{{ object.email }} </p>
			<p class="text-muted mb-0" style="font-size: 12px">Phone:</p>
			<p>{{ object.phone }} </p>
			<p class="text-muted mb-0" style="font-size: 12px">Room:</p>
			<p>{{ object.room }} </p>
			<p class="text-muted mb-0" style="font-size: 12px">Subjects:</p>
			<p><ul>{% for subject in object.subjects.all %}<li>{{ subject }}</li>{% endfor %}</ul></p>
		</div>
	</div>
</div>  
{% endblock %}

src/templates/directory/teacher_list.html
{% extends 'base.html' %}
{% block title %}Home::Teacher Listing{% endblock %}
{% block content %}
<div class="form-row">
    <form action="{% url 'directory:search' %}">
        <label for="choice">Filter by:</label>
            <select id="choice" name="choice" class="form-select form-select-lg mb-3">
                <option value="lname">Last Name</option>
                <option value="subject">Subject</option>
            </select>
            <input type="text" class="form" name="q" placeholder="Starts with....">
            <input type="submit" value="Filter">
            <!--<span class="input-group-btn"></span>
                <button class="fa fa-search" type="button">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>-->
    </form>
</div>
<div label="table">
        <table class="table table-bordered table-striped table-hover mt-3">
            <thead class="thead-dark">
                <tr>
                    <th class="w-25">Name</th>
                    <th class="w-25">Email</th>
                    <th class="w-25">Phone</th>
                    <th class="w-10">Room</th>
                    <th class="w-50">Subjects</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'directory:detail' object.id %}"> {{ object.first_name }} {{ object.last_name }}</td>
                    <td>{{ object.email }}</td>
                    <td>{{ object.phone }}</td>
                    <td>{{ object.room }}</td>
                    <td><ul>{% for subject in object.subjects.all %}<li>{{ subject }}</li>{% endfor %}</ul></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>

        
{% endblock %}
{% block scripts %}
{% endblock %}

src/templates/importer/import.html
{% extends 'base.html' %}
{% block title %}Importer{% endblock %}
{% block content %}
		<div style="width: 500px; margin: auto;">
			<fieldset name="Multiple Files Upload">
				{% if msg %} {% autoescape off %} {{ msg }} {% endautoescape %} {% endif %}
				<form method="post" action="{% url 'importer:import-files' %}" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.as_p }}
						<input type="submit" value="Upload">
					</p>
				</form>
			</fieldset>
		</div>
{% endblock %}